version: 2.1

jobs:
  test:
    working_directory: ~
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: check versions
          command: |
            python --version
            pip --version
      - run:
          name: install dependencies
          command: sudo pip install -r requirements.txt

workflows:
  test:
    jobs:
      - test