version: 2.1

jobs:
  test:
    working_directory: ~
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
            python --version
            pip --version
      - run:
          name: Install dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            mkdir -p /tmp/test-results
            pytest --junitxml=/tmp/test-results/out_report.xml
      - store_test_results:
          path: /tmp/test-results


workflows:
  test:
    jobs:
      - test